name: Mobile Automation Pipeline (Fixed Docker Solution)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Android Emulator in Docker
        run: |
          # Usando a imagem oficial do Android Emulator
          docker run -d \
            --name android-emulator \
            --privileged \
            -p 5554:5554 \
            -p 5555:5555 \
            -e ANDROID_DEVICE="Nexus 5" \
            -e ANDROID_VERSION=30 \
            -e EMULATOR_ARGS="-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim" \
            -v $(pwd):/root/tests \
            -w /root/tests \
            ghcr.io/butomo1989/docker-android-emulator:latest

          # Wait for emulator to be ready
          for i in {1..60}; do
            if docker exec android-emulator adb shell getprop sys.boot_completed | grep -q "1"; then
              echo "Emulator ready!"
              break
            fi
            echo "Waiting for emulator... Attempt $i/60"
            sleep 5
          done

          # Verificação final
          docker exec android-emulator adb devices
          docker exec android-emulator adb shell getprop

      - name: Run Tests
        run: |
          robot --variable APPIUM_URL:http://localhost:4723 \
                --outputdir results \
                --log log.html \
                --report report.html \
                features/

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/

      - name: Clean up
        if: always()
        run: |
          docker stop android-emulator || true
          docker rm android-emulator || true
