name: Mobile Automation Pipeline (Native Solution)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g appium@2.0.0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH" >> $GITHUB_PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" -f

      - name: Start Emulator
        run: |
          emulator -avd test -no-audio -no-window -no-snapshot -gpu swiftshader_indirect -no-accel -memory 2048 &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0
          
          # Robust wait for emulator
          for i in {1..30}; do
            if adb shell getprop sys.boot_completed | grep -q "1"; then
              echo "Emulator ready after $i attempts"
              break
            fi
            echo "Waiting for emulator... Attempt $i/30"
            sleep 5
          done

      - name: Start Appium
        run: |
          appium --relaxed-security --log-timestamp --local-timezone --allow-insecure chromedriver_autodownload &
          sleep 15
          curl http://localhost:4723/wd/hub/status || true

      - name: Run Tests
        run: |
          robot --variable APPIUM_URL:http://localhost:4723 \
                --outputdir results \
                --log log.html \
                --report report.html \
                features/

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/

      - name: Clean up
        if: always()
        run: |
          adb kill-server || true
          pkill -9 qemu-system-x86_64 || true
          pkill -9 node || true
