name: Mobile Tests Pipeline

on:
  push:
    branches:
      - main  # Executa quando há push na branch main
  pull_request:
    branches:
      - main  # Executa quando há um pull request para a branch main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa um runner com Ubuntu

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Versão do Python que você usa

      # Passo 3: Instalar o Poetry
      - name: Install Poetry
        run: |
          pip install poetry

      # Passo 4: Instalar dependências com Poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root

      # Passo 5: Instalar o Appium
      - name: Install Appium
        run: |
          npm install -g appium

      # Passo 6: Iniciar o servidor Appium em segundo plano
      - name: Start Appium server
        run: |
          appium --log-level error --allow-insecure chromedriver_autodownload &
          sleep 10  # Espera o servidor iniciar

      # Passo 7: Executar os testes com Poetry
      - name: Run tests
        run: |
          poetry run robot --outputdir results --log log.html --report report.html features/

      # Passo 8: Publicar os resultados dos testes
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
