name: Mobile Tests Pipeline (Appium Android Action)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Appium Android
        uses: marketplace-actions/appium-android-action@v1
        with:
          device: "Samsung Galaxy S10"
          api-level: 30

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Appium server
        run: |
          appium --allow-insecure chromedriver_autodownload &
          sleep 20

      - name: Execute tests
        run: |
          robot --outputdir results --log log.html --report report.html features/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
