name: Mobile Automation Pipeline (Docker Solution)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Android Emulator in Docker
        run: |
          docker run -d \
            --name android-emulator \
            --privileged \
            -p 5554:5554 \
            -p 5555:5555 \
            -e DEVICE="Pixel 4" \
            -e ANDROID_ARCH="x86_64" \
            -e API_LEVEL=30 \
            -e EMULATOR_OPTIONS="-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim" \
            -v $(pwd):/root/tests \
            -w /root/tests \
            budtmo/docker-android-x86-11.0

          # Wait for emulator to be ready
          docker exec android-emulator bash -c '
          for i in {1..60}; do
            if adb shell getprop sys.boot_completed | grep -q "1"; then
              echo "Emulator ready!"
              exit 0
            fi
            echo "Waiting for emulator... Attempt $i/60"
            sleep 5
          done
          echo "Emulator failed to start"
          exit 1
          '

      - name: Run Tests
        run: |
          robot --variable APPIUM_URL:http://localhost:4723 \
                --outputdir results \
                --log log.html \
                --report report.html \
                features/

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/

      - name: Clean up
        if: always()
        run: |
          docker stop android-emulator || true
          docker rm android-emulator || true
