name: Mobile Tests Pipeline (Docker)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Docker e executar os testes
      - name: Run tests in Docker
        run: |
          docker run --rm --privileged \
          -v $PWD:/root/tests \
          -w /root/tests \
          -e DEVICE="Samsung Galaxy S10" \
          -e APPIUM=true \
          ghcr.io/marketplace-actions/appium-android-action/ubuntu:v1.0.0 \
          bash -c "
          pip install -r requirements.txt && \
          appium --allow-insecure chromedriver_autodownload & \
          sleep 20 && \
          robot --outputdir results --log log.html --report report.html features/
          "
      
      # Passo 3: Publicar os resultados dos testes
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
