name: Mobile Tests Pipeline (Official Appium Docker)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with official Appium image
        run: |
          docker run --rm \
          -v $PWD:/root/tests \
          -w /root/tests \
          -e APPIUM_HOST=127.0.0.1 \
          -e APPIUM_PORT=4723 \
          --privileged \
          appium/appium \
          bash -c "
          pip install -r requirements.txt && \
          appium --allow-insecure chromedriver_autodownload & \
          sleep 20 && \
          adb start-server && \
          robot --outputdir results --log log.html --report report.html features/
          "

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
